server:
  port: 8082

spring:
  application:
    name: operaciones-service


  datasource:
    url: jdbc:h2:file:/data/operacionesdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true   # corre data.sql tras crear el schema

  h2:
    console:
      enabled: true
      path: /h2

      #sacar esta linea mas adelante si no se necesita acceso remoto al H2
      settings:
        web-allow-others: true  

  sql:
    init:
      mode: embedded

  jackson:
    time-zone: America/Argentina/Buenos_Aires

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Si este servicio consume Maestros, te conviene centralizar las URLs ac√°
clients:
  maestros:
    base-url: http://maestros-service:8081
