server:
  port: 8081

spring:
  application:
    name: maestros-service
# --- CONFIGURACIÓN DE LA BASE DE DATOS ---
  datasource:
    url: jdbc:postgresql://maestros-db:5432/maestrosdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
# --- CONFIGURACIÓN DE JPA (Hibernate) ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true